# Generated by Django 4.2.5 on 2023-09-13 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='fullname',
            field=models.CharField(help_text='ФИО', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(help_text='Должность', on_delete=django.db.models.deletion.CASCADE, to='employee_app.position'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, help_text='Зарплата', max_digits=15),
        ),
    ]
